import type { UiTranslationKey } from '../../../data/uiTranslations'
import type {
  OverviewWidgetId,
  OverviewWidgetSizeHint,
  OverviewWidgetVisibility,
  OverviewWidgetWidth,
} from '../../../utils/overview/overviewLayout'
import { OVERVIEW_WIDGET_SIZE_WEIGHT } from '../../../utils/overview/overviewLayout'

export interface OverviewWidgetDefinition {
  id: OverviewWidgetId
  titleKey: UiTranslationKey
  descriptionKey: UiTranslationKey
  defaultWidth: OverviewWidgetWidth
  /** Relative vertical footprint for column packing (compact one-liners vs tall cards). */
  sizeHint: OverviewWidgetSizeHint
  /** Widget can only appear once in the layout. */
  singleton: boolean
  visibility: OverviewWidgetVisibility
}

export const OVERVIEW_WIDGET_REGISTRY: Record<OverviewWidgetId, OverviewWidgetDefinition> = {
  'hero-summary': {
    id: 'hero-summary',
    titleKey: 'overviewWidgetHeroSummary',
    descriptionKey: 'overviewWidgetDescHeroSummary',
    defaultWidth: 'full',
    sizeHint: 'compact',
    singleton: true,
    visibility: 'always',
  },
  safety: {
    id: 'safety',
    titleKey: 'overviewWidgetSafety',
    descriptionKey: 'overviewWidgetDescSafety',
    defaultWidth: 'full',
    sizeHint: 'tall',
    singleton: true,
    visibility: 'always',
  },
  medication: {
    id: 'medication',
    titleKey: 'overviewWidgetMedication',
    descriptionKey: 'overviewWidgetDescMedication',
    defaultWidth: 'half',
    sizeHint: 'tall',
    singleton: true,
    visibility: 'always',
  },
  diagnoses: {
    id: 'diagnoses',
    titleKey: 'overviewWidgetDiagnoses',
    descriptionKey: 'overviewWidgetDescDiagnoses',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'always',
  },
  psychopathology: {
    id: 'psychopathology',
    titleKey: 'overviewWidgetPsychopathology',
    descriptionKey: 'overviewWidgetDescPsychopathology',
    defaultWidth: 'full',
    sizeHint: 'tall',
    singleton: true,
    visibility: 'always',
  },
  'labs-due': {
    id: 'labs-due',
    titleKey: 'overviewWidgetLabsDue',
    descriptionKey: 'overviewWidgetDescLabsDue',
    defaultWidth: 'full',
    sizeHint: 'tall',
    singleton: true,
    visibility: 'always',
  },
  'prior-therapies': {
    id: 'prior-therapies',
    titleKey: 'overviewWidgetPriorTherapies',
    descriptionKey: 'overviewWidgetDescPriorTherapies',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'always',
  },
  'spiegel-all': {
    id: 'spiegel-all',
    titleKey: 'overviewWidgetSpiegelAll',
    descriptionKey: 'overviewWidgetDescSpiegelAll',
    defaultWidth: 'full',
    sizeHint: 'tall',
    singleton: true,
    visibility: 'hasSpiegel',
  },
  'recent-verlauf': {
    id: 'recent-verlauf',
    titleKey: 'overviewWidgetRecentVerlauf',
    descriptionKey: 'overviewWidgetDescRecentVerlauf',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'always',
  },
  appointments: {
    id: 'appointments',
    titleKey: 'overviewWidgetAppointments',
    descriptionKey: 'overviewWidgetDescAppointments',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'always',
  },
  dokumentation: {
    id: 'dokumentation',
    titleKey: 'overviewWidgetDokumentation',
    descriptionKey: 'overviewWidgetDescDokumentation',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'always',
  },
  psychotherapy: {
    id: 'psychotherapy',
    titleKey: 'overviewWidgetPsychotherapy',
    descriptionKey: 'overviewWidgetDescPsychotherapy',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'hasPsychotherapy',
  },
  'isdm-summary': {
    id: 'isdm-summary',
    titleKey: 'overviewWidgetIsdmSummary',
    descriptionKey: 'overviewWidgetDescIsdmSummary',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'hasIsdm',
  },
  collaboration: {
    id: 'collaboration',
    titleKey: 'overviewWidgetCollaboration',
    descriptionKey: 'overviewWidgetDescCollaboration',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'always',
  },
  'lab-results': {
    id: 'lab-results',
    titleKey: 'overviewWidgetLabResults',
    descriptionKey: 'overviewWidgetDescLabResults',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'hasLabData',
  },
  'butterfly-criteria': {
    id: 'butterfly-criteria',
    titleKey: 'overviewWidgetButterflyCriteria',
    descriptionKey: 'overviewWidgetDescButterflyCriteria',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'hasButterfly',
  },
  zwangsmassnahme: {
    id: 'zwangsmassnahme',
    titleKey: 'overviewWidgetZwangsmassnahme',
    descriptionKey: 'overviewWidgetDescZwangsmassnahme',
    defaultWidth: 'half',
    sizeHint: 'compact',
    singleton: true,
    visibility: 'hasZwangsmassnahme',
  },
  verlaufstendenz: {
    id: 'verlaufstendenz',
    titleKey: 'overviewWidgetVerlaufstendenz',
    descriptionKey: 'overviewWidgetDescVerlaufstendenz',
    defaultWidth: 'full',
    sizeHint: 'compact',
    singleton: true,
    visibility: 'always',
  },
  'ekg-summary': {
    id: 'ekg-summary',
    titleKey: 'overviewWidgetEkgSummary',
    descriptionKey: 'overviewWidgetDescEkgSummary',
    defaultWidth: 'half',
    sizeHint: 'compact',
    singleton: true,
    visibility: 'hasEkg',
  },
  'eeg-summary': {
    id: 'eeg-summary',
    titleKey: 'overviewWidgetEegSummary',
    descriptionKey: 'overviewWidgetDescEegSummary',
    defaultWidth: 'half',
    sizeHint: 'compact',
    singleton: true,
    visibility: 'hasEeg',
  },
  'ct-summary': {
    id: 'ct-summary',
    titleKey: 'overviewWidgetCtSummary',
    descriptionKey: 'overviewWidgetDescCtSummary',
    defaultWidth: 'half',
    sizeHint: 'compact',
    singleton: true,
    visibility: 'hasCt',
  },
  'angemeldete-therapien': {
    id: 'angemeldete-therapien',
    titleKey: 'overviewWidgetAngemeldeteTherapien',
    descriptionKey: 'overviewWidgetDescAngemeldeteTherapien',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'always',
  },
  compliance: {
    id: 'compliance',
    titleKey: 'overviewWidgetCompliance',
    descriptionKey: 'overviewWidgetDescCompliance',
    defaultWidth: 'half',
    sizeHint: 'compact',
    singleton: true,
    visibility: 'always',
  },
  'ci-dimensional': {
    id: 'ci-dimensional',
    titleKey: 'overviewWidgetCiDimensional',
    descriptionKey: 'overviewWidgetDescCiDimensional',
    defaultWidth: 'half',
    sizeHint: 'tall',
    singleton: true,
    visibility: 'clinicalIntelligenceEnabled',
  },
  'ci-mechanism': {
    id: 'ci-mechanism',
    titleKey: 'overviewWidgetCiMechanism',
    descriptionKey: 'overviewWidgetDescCiMechanism',
    defaultWidth: 'half',
    sizeHint: 'tall',
    singleton: true,
    visibility: 'clinicalIntelligenceEnabled',
  },
  'ci-status': {
    id: 'ci-status',
    titleKey: 'overviewWidgetCiStatus',
    descriptionKey: 'overviewWidgetDescCiStatus',
    defaultWidth: 'half',
    sizeHint: 'standard',
    singleton: true,
    visibility: 'clinicalIntelligenceEnabled',
  },
}

export const OVERVIEW_WIDGET_LIST = Object.values(OVERVIEW_WIDGET_REGISTRY)

export function getOverviewWidgetSizeWeight(widgetId: OverviewWidgetId): number {
  return OVERVIEW_WIDGET_SIZE_WEIGHT[OVERVIEW_WIDGET_REGISTRY[widgetId].sizeHint]
}
